package com.capstone.contact.access.model

import com.capstone.contact.R


object ContactDummy
{
    val RandomContact = listOf(
        Contacts(id = 0, fullName = "Angelina Jolie", hp = "1234567890", address = "456 Hollywood Boulevard, Los Angeles", ig = "@angelinajolie", email = "angelina@example.com", desc = "Angelina Jolie adalah seorang aktris dan sutradara terkenal yang telah berperan dalam banyak film sukses seperti \"Tomb Raider\" dan \"Maleficent\". Dia juga dikenal karena keterlibatannya dalam pekerjaan kemanusiaan.", img = R.drawable.angelina),
        Contacts(id = 1, fullName = "Beyoncé Knowles", hp = "9876543210", address = "789 Music Avenue, Houston", ig = "@beyonce", email = "beyonce@example.com", desc = "Beyoncé Knowles adalah seorang penyanyi, penulis lagu, dan aktris terkenal. Dia telah merilis banyak lagu hits dan memenangkan berbagai penghargaan musik termasuk Grammy Awards.)", img =R.drawable.beyonce),
        Contacts(id = 2, fullName = "Cristiano Ronaldo", hp = "5551234567", address = "246 Football Street, Turin", ig = "@cristiano", email = "cristiano@example.com", desc = "Cristiano Ronaldo adalah seorang pemain sepak bola Portugal yang dianggap sebagai salah satu pemain terbaik dalam sejarah olahraga. Dia telah meraih banyak gelar dan penghargaan selama kariernya.", img =R.drawable.ronaldo),
        Contacts(id = 3, fullName = "LeBron James", hp = "3216549870", address = "135 Basketball Court, Los Angeles", ig = "@kingjames", email = "lebron@example.com", desc = "LeBron James adalah seorang pemain basket profesional Amerika yang dianggap sebagai salah satu pemain terbaik dalam sejarah NBA. Dia memiliki karir yang cemerlang dengan beberapa tim NBA dan telah memenangkan banyak penghargaan individu dan kejuaraan.", img = R.drawable.lebron),
        Contacts(id = 4, fullName = "Scarlett Johansson", hp = "8885551234", address = "864 Beauty Lane, New York", ig = "@scarlettjohansson", email = "scarlett@example.com", desc = "Scarlett Johansson adalah seorang aktris terkenal yang telah membintangi banyak film populer seperti \"The Avengers\" dan \"Lost in Translation\". Dia juga dikenal karena kecantikan dan bakat aktingnya.", img = R.drawable.scarlett),
        Contacts(id = 5, fullName = "Narenda Wicaksono", hp = "7778889999", address = "579 Tech Street, Jakarta", ig = "@narenda", email = "narenda@example.com", desc = "Narenda adalah seorang CEO Dicoding. Dia memiliki pengetahuan mendalam tentang pemrograman, pengembangan aplikasi, dan teknologi terkini. Dia sering berbagi ulasan dan panduan yang informatif di komunitas teknologi.", img = R.drawable.narenda),
        Contacts(id = 6, fullName = "Tom Hanks", hp = "1112223333", address = "789 Hollywood Boulevard, Los Angeles", ig = "@tomhanks", email = "tom@example.com", desc = "Tom Hanks adalah seorang aktor terkenal yang telah berperan dalam berbagai film sukses seperti \"Forrest Gump\" dan \"Cast Away\". Dia dianggap sebagai salah satu aktor terbaik dalam industri film.", img = R.drawable.tom),
        Contacts(id = 7, fullName = "Adele", hp = "4445556666", address = "246 Music Avenue, London", ig = "@adele", email = "adele@example.com", desc = "Adele adalah seorang penyanyi dan penulis lagu yang terkenal dengan suara emasnya. Dia telah merilis lagu-lagu hit yang memenangkan Grammy Awards dan memikat hati pendengar di seluruh dunia.", img = R.drawable.adele),
        Contacts(id = 8, fullName = "Neymar Jr", hp = "7778889999", address = "135 Football Street, Paris", ig = "@neymarjr", email = "neymar@example.com", desc = "Neymar Jr. adalah seorang pemain sepak bola Brasil yang bermain untuk klub Paris Saint-Germain dan tim nasional Brasil. Dia dikenal dengan keterampilan teknisnya yang luar biasa dan menjadi salah satu pemain terbaik dalam permainan.", img =R.drawable.neymar),
        Contacts(id = 9, fullName = "Kobe Bryant", hp = "9998887777", address = "864 Basketball Court, Los Angeles", ig = "@kobebryant", email = "kobe@example.com", desc = "Kobe Bryant adalah mantan pemain basket profesional Amerika yang dianggap sebagai salah satu pemain terbaik dalam sejarah NBA. Dia memiliki kariernya yang mengesankan bersama Los Angeles Lakers dan memenangkan banyak penghargaan dan gelar.\"", img =R.drawable.kobe), ) }